---
# tasks file for mate-desktop

- name: Install ubuntu mate desktop basic
  apt:
    name: ubuntu-mate-desktop
    state: present
    install_recommends: no
  tags: [install]
  become: yes

- name: Install additional desktop packages
  apt:
    name: "{{ mate_recommends }}"
    state: present
  tags: [install]
  become: yes

- name: dconf settings (theming)
  copy: 
    src: "{{ mate_dconf_src }}"
    dest: /etc
  notify:
    - dconf-update
  tags: [install, config]
  become: yes
