---
# tasks file for mate-desktop

- name: Install ubuntu mate desktop basic
  ansible.builtin.apt:
    name: ubuntu-mate-desktop
    state: present
    install_recommends: false
  tags: [install]
  become: true

- name: Install additional desktop packages
  ansible.builtin.apt:
    name: "{{ mate_recommends }}"
    state: present
  tags: [install]
  become: true

- name: dconf settings (theming)
  ansible.builtin.copy:
    src: "{{ mate_dconf_src }}"
    dest: /etc
    mode: preserve
  notify:
    - dconf-update
  tags: [install, config]
  become: true
